### ISSUE TITLE
Using AEO-Light by command line (OSX)?

### ISSUE THREAD

**Issue by mikmake** [usc-imi/aeo-light#11]
Hi there, 
Since it ´s frustratingly slow to open a folder that contains large amounts of dpx files, i´d like to know if it´s possible to open a new project by using Terminal? I´m inexperienced working with command line but  propably somebody could help me out and point me the right direction?
Thanks, 
Mikko

**Comment by kieranjol** [comment]
I would also love a CLI option.we automate much of our processes via the
command line.iy would make a huge difference.

**Comment by retokromer** [comment]
The problem is that we have to set the parameters for each file, if we wish to achieve the best result, when working on legacy materials. I personally don’t think this can be automated at the same quality level. Yet, of course, I would be happy to be wrong!

**Comment by sjohnson-imi** [comment]
While there's no CLI, you can get some relief from the frustration of trying to set up a new project when the source is a folder of DPX files. The key is that project files are stored as plain text, so you could creating your own AEO-Light project file via a text editor instead (use an existing one as a template). Opening the project file instead of selecting a DPX file to start will avoid forcing the GUI FileBrowser to sort that folder's DPX files.

**Comment by wilsbacher** [comment]
I'm going to try Scott's suggestion, which sounds helpful in some instances. But I agree with Reto that one of the real benefits of AEO-light 2 is the ability to make adjustments to the pixel information using the Image settings and then A/B test samples to identify the best audio.

**Comment by mikmake** [comment]
Thanks for the tip Scott. This is just what I was looking for, only by different means. Also agree that all the rest adjustments is best to do manually and by ear.
