### ISSUE TITLE
Error extracting sound

### ISSUE THREAD

**Issue by ghopretz** [usc-imi/aeo-light#33]
![Annotation 2020-08-06 235102](https://user-images.githubusercontent.com/8053983/89559331-b9cd4c00-d83f-11ea-9550-959c6279507e.png)

![Annotation 2020-08-06 235222](https://user-images.githubusercontent.com/8053983/89559476-e97c5400-d83f-11ea-81ea-6a08137768a8.png)

How to solve that problem?

**Comment by maheelrp** [comment]
I am having the same issue in Win10 . Also when I try to run the software from the created .exe file  there is an error message. See screen grab. Any solution Please. 
![image](https://user-images.githubusercontent.com/7518351/103530768-0760ea00-4eae-11eb-82bb-ceb7553cb62d.png)

**Comment by taschenbach** [comment]
@ghopretz The problem is being caused by using a non intraframe codec. While this should not occur, there wasn't much testing for temporal codecs and because of the nature of optical sound these codecs are not recommended for use. 

@maheelrp In the image you posted you are not using the current version. There are no Matlab references in any of the current versions. Also the executable name in the command prompt title bar is not the current version executable name.

**Comment by wilsbacher** [comment]
@maheelrp Please upgrade to AEO-light 2.3.3 release available here, https://github.com/usc-imi/aeo-light/releases/tag/2.3.3

**Comment by maheelrp** [comment]
Thanks for the responses.
